config/routes.rb
Rails.application.routes.draw do
  resources :formulas

  resources :variables

  get 'interfaces/index'

  resources :task_types do
    resources :tasks
  end

  resources :interfaces do
    resources :missions
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'interfaces#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/formula.rb
class Formula < ActiveRecord::Base
  has_and_belongs_to_many :tasks
  has_many :missions
end

app/controllers/formulas_controller.rb
class FormulasController < InheritedResources::Base

  private

    def formula_params
      params.require(:formula).permit(:name, :description)
    end
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/views/formulas/_form.html.erb
<%= simple_form_for(@formula) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :task %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/formulas/edit.html.erb
<h1>Editing formula</h1>

<%= render 'form' %>

<%= link_to 'Show', @formula %> |
<%= link_to 'Back', formulas_path %>

app/views/formulas/index.html.erb
<h1>Listing formulas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @formulas.each do |formula| %>
      <tr>
        <td><%= formula.name %></td>
        <td><%= formula.description %></td>
        <td><%= formula.task %></td>
        <td><%= link_to 'Show', formula %></td>
        <td><%= link_to 'Edit', edit_formula_path(formula) %></td>
        <td><%= link_to 'Destroy', formula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Formula', new_formula_path %>

app/views/formulas/new.html.erb
<h1>New formula</h1>

<%= render 'form' %>

<%= link_to 'Back', formulas_path %>

app/views/formulas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @formula.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @formula.description %>
</p>

<p>
  <strong>Task:</strong>
  <%= @formula.task %>
</p>

<%= link_to 'Edit', edit_formula_path(@formula) %> |
<%= link_to 'Back', formulas_path %>