config/routes.rb
Rails.application.routes.draw do
  resources :formulas

  resources :variables

  get 'interfaces/index'

  resources :task_types do
    resources :tasks
  end

  resources :interfaces do
    resources :missions
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'interfaces#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/interface.rb
class Interface < ActiveRecord::Base
  belongs_to :user
  has_many :missions
end

app/controllers/interfaces_controller.rb
class InterfacesController < ApplicationController
  
  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :authenticate_user!, only: [:index]
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]
  
  before_action :set_interface, only: [:show, :edit, :update, :destroy]
  
  # GET /interfaces
  # GET /interfaces.json
  def index
    @interfaces = Interface.all
  end

  # GET /interfaces/1
  # GET /interfaces/1.json
  def show
  end
  
  # GET /interfaces/new
  def new
    @interface = Interface.new
  end

  # GET /interfaces/1/edit
  def edit
  end

  # POST /interfaces
  # POST /interfaces.json
  def create
    @interface = Interface.new(interface_params)
    @interface.user = current_user

    respond_to do |format|
      if @interface.save
        format.html { redirect_to @interface, notice: 'Interface was successfully created.' }
        format.json { render :show, status: :created, location: @interface }
      else
        format.html { render :new }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interfaces/1
  # PATCH/PUT /interfaces/1.json
  def update
    respond_to do |format|
      if @interface.update(interface_params)
        format.html { redirect_to @interface, notice: 'Interface was successfully updated.' }
        format.json { render :show, status: :ok, location: @interface }
      else
        format.html { render :edit }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interfaces/1
  # DELETE /interfaces/1.json
  def destroy
    @interface.destroy
    respond_to do |format|
      format.html { redirect_to interfaces_url, notice: 'Interface was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interface
      @interface = Interface.find(params[:id])
      @missions = Mission.where(interface: @interface)
      redirect_to interfaces_path and return unless is_users?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interface_params
      params.require(:interface).permit(:address, :credentials, :user_id)
    end
    
    def is_users?
      @interface.user == current_user
    end
end

app/helpers/interfaces_helper.rb
module InterfacesHelper
end

app/views/interfaces/_form.html.erb
<%= form_for @interface, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group hide">
    <%= f.label :address, :class => 'control-label col-md-2 hide' %>
    <div class="col-md-10 hide">
      <%= f.text_field :address, :class => 'text-field form-control hide' %>
    </div>
  </div>
  <div class="form-group hide">
    <%= f.label :credentials, :class => 'control-label col-md-2 hide' %>
    <div class="col-md-10">
      <%= f.text_field :credentials, :class => 'text-field form-control hide' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  interfaces_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/interfaces/edit.html.erb
<%- model_class = Interface -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Interface %></h1>
</div>
<%= render :partial => 'form' %>

app/views/interfaces/index.html.erb
<%- model_class = Interface -%>
<div class="page-header">
  <h1><%=t '.title', :default => Interface %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:credentials) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @interfaces.each do |interface| %>
      <tr>
        <td><%= interface.id %></td>
        <td><%= interface.address %></td>
        <td><%= interface.credentials %></td>
        <td><%=l interface.created_at, format: :long %></td>
        <td>
          <%= link_to interface_path(interface), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to interface_path(interface), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_interface_path,
            :class => 'btn btn-primary' %>

app/views/interfaces/new.html.erb
<%- model_class = Interface -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Interface %></h1>
</div>
<%= render :partial => 'form' %>

app/views/interfaces/show.html.erb
<%- model_class = Interface -%>
<div class="page-header">
  <h1><%=t '.title', :default => Interface %></h1>
</div>

<%- model_class = Mission -%>
<div class="fieldset subindex">
	<h2>Missions</h2>

	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th>ID</th>
	      <th><%= model_class.human_attribute_name(:formula_id) %></th>
	      <th><%= model_class.human_attribute_name(:variables) %></th>
	      <th><%= model_class.human_attribute_name(:created_at) %></th>
	      <th><%=t '.actions', :default => t("helpers.actions") %></th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @interface.missions.each do |mission| %>
	      <tr>
	        <td><%= mission.id %></td>
	        <td><%= mission.formula.name %></td>
	        <td>
						<table class="missions_variables_table">
							<thead>
								<th>name</th>
								<th>value</th>
							</thead>
							<tbody>
								<% JSON.parse(mission.variables || "{}").each do |k,v| %>
								<tr>
									<td><%= "#{k}" %></td>
									<td><%= "#{v}" %></td>
								</tr>
								<% end %>
							</tbody>
						</table>
					</ul>
					</td>
	        <td><%=l mission.created_at, format: :long %></td>
	        <td>
	          <%= link_to interface_mission_path(@interface, mission), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
	            <%= glyph 'info-sign' %>
	            <%= glyph 'pencil' %>
	          <%- end -%>
	          <%= link_to interface_mission_path(@interface, mission), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
	            <%= glyph 'remove' %>
	          <%- end -%>
	        </td>
	      </tr>
	    <% end %>
		</tbody>
	</table>
	<%= link_to t('.new', :default => t("helpers.links.new")),
	            new_interface_mission_path(@interface),
	            :class => 'btn btn-primary' %>
</div>

<%- model_class = Interface -%>
<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address) %></dt>
      <dd><pre class="prettyprint"><%= @interface.address.blank? ? " " : @interface.address %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:credentials) %></dt>
      <dd><pre class="prettyprint"><%= @interface.credentials.blank? ? " " : @interface.credentials %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              interfaces_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_interface_path(@interface), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              interface_path(@interface),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>