config/routes.rb
Rails.application.routes.draw do
  resources :formulas

  resources :variables

  get 'interfaces/index'

  resources :task_types do
    resources :tasks
  end

  resources :interfaces do
    resources :missions
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'interfaces#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/variable.rb
class Variable < ActiveRecord::Base
  belongs_to :task
  belongs_to :task_type
end

app/controllers/variables_controller.rb
class VariablesController < InheritedResources::Base

  private

    def variable_params
      params.require(:variable).permit(:prompt, :name, :validation_type, :validation, :task_id, :task_type_id)
    end
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/variables/_form.html.erb
<%= simple_form_for(@variable) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :prompt %>
    <%= f.input :name %>
    <%= f.input :validation_type %>
    <%= f.input :validation %>
    <%= f.association :task %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/variables/edit.html.erb
<h1>Editing variable</h1>

<%= render 'form' %>

<%= link_to 'Show', @variable %> |
<%= link_to 'Back', variables_path %>

app/views/variables/index.html.erb
<h1>Listing variables</h1>

<table>
  <thead>
    <tr>
      <th>Prompt</th>
      <th>Name</th>
      <th>Validation type</th>
      <th>Validation</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variables.each do |variable| %>
      <tr>
        <td><%= variable.prompt %></td>
        <td><%= variable.name %></td>
        <td><%= variable.validation_type %></td>
        <td><%= variable.validation %></td>
        <td><%= variable.task %></td>
        <td><%= link_to 'Show', variable %></td>
        <td><%= link_to 'Edit', edit_variable_path(variable) %></td>
        <td><%= link_to 'Destroy', variable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variable', new_variable_path %>

app/views/variables/new.html.erb
<h1>New variable</h1>

<%= render 'form' %>

<%= link_to 'Back', variables_path %>

app/views/variables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prompt:</strong>
  <%= @variable.prompt %>
</p>

<p>
  <strong>Name:</strong>
  <%= @variable.name %>
</p>

<p>
  <strong>Validation type:</strong>
  <%= @variable.validation_type %>
</p>

<p>
  <strong>Validation:</strong>
  <%= @variable.validation %>
</p>

<p>
  <strong>Task:</strong>
  <%= @variable.task %>
</p>

<%= link_to 'Edit', edit_variable_path(@variable) %> |
<%= link_to 'Back', variables_path %>